### ISSUE TITLE
https://www.readwithu.com/ 无了

### ISSUE THREAD

**Issue by ghost** [TwoWater/Python#100]
[gitbook](https://www.readwithu.com/)无了

**Comment by mrzhanggit** [comment]
您好，您发来的邮件已经收到。谢谢！

**Comment by sorever** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 999999VVV** [comment]
来件已收到，确认后会回复给你哦

**Comment by kbzyjp** [comment]
你好，你的邮件已经收到。

**Comment by ghost** [comment]
仔细康一下[这个](https://github.com/walter201230/Python/blob/master/Res/Python%E5%8D%9A%E5%AE%A2%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90.md)

**Comment by 999999VVV** [comment]
来件已收到，确认后会回复给你哦

**Comment by mrzhanggit** [comment]
您好，您发来的邮件已经收到。谢谢！

**Comment by kbzyjp** [comment]
你好，你的邮件已经收到。

**Comment by sorever** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
