### ISSUE TITLE
编码规范换行

### ISSUE THREAD

**Issue by brivencn** [TwoWater/Python#27]
print 'Hello, '\
      '%s %s!' %\
      ('Harry', 'Potter')
我是新手才学 这里是不是忘记给print方法加括号了，我加了括号没问题，不加报错呢

**Comment by TwoWater** [comment]
> print 'Hello, '
> '%s %s!' %
> ('Harry', 'Potter')
> 我是新手才学 这里是不是忘记给print方法加括号了，我加了括号没问题，不加报错呢

是的，python3 要加括号

**Comment by TwoWater** [comment]
> print 'Hello, '
> '%s %s!' %
> ('Harry', 'Potter')
> 我是新手才学 这里是不是忘记给print方法加括号了，我加了括号没问题，不加报错呢

感谢您，我修改一下

**Comment by brivencn** [comment]
感谢您才对，我才开始学今天第二天，我做PHP的，昨天看了一天官方文档，今天如获至宝呢
