### ISSUE TITLE
关于“类和对象”章节中“不管实例对象怎么修改属性值，对类的属性还是没有影响的."疑问

### ISSUE THREAD

**Issue by kszhaofeng** [TwoWater/Python#29]
“不管实例对象怎么修改属性值，对类的属性还是没有影响的."实际测试中都有影响的。下面是测试的代码和结果``
```
class ClassA():
	var1 = 'AAA'	
	def fun1(p):
		print('fun1'+p.var1)	
		
a = ClassA
print(a.var1)

a.var1 = 'CCC'
print(a.var1)
print(ClassA.var1)
```
![123](https://user-images.githubusercontent.com/7122448/69700253-f11e2180-1124-11ea-996b-390187f2e200.png)
是版本问题还是其他什么原因，麻烦楼主解惑。

**Comment by TwoWater** [comment]
> “不管实例对象怎么修改属性值，对类的属性还是没有影响的."实际测试中都有影响的。下面是测试的代码和结果``
> 
> ```
> class ClassA():
> 	var1 = 'AAA'	
> 	def fun1(p):
> 		print('fun1'+p.var1)	
> 		
> a = ClassA
> print(a.var1)
> 
> a.var1 = 'CCC'
> print(a.var1)
> print(ClassA.var1)
> ```
> 
> ![123](https://user-images.githubusercontent.com/7122448/69700253-f11e2180-1124-11ea-996b-390187f2e200.png)
> 是版本问题还是其他什么原因，麻烦楼主解惑。

我告诉你问题出在哪里，至于原因，我还是因为你自己能想一下，因为我直接说出来，你自己不去想，其实对你用处不大。如果不懂可以再问。
a = ClassA

**Comment by TwoWater** [comment]
我 github 回复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kszhaofeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 下午2:50
收件人:&nbsp;"TwoWater/Python"<Python@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TwoWater/Python] 关于“类和对象”章节中“不管实例对象怎么修改属性值，对类的属性还是没有影响的."疑问 (#29)




“不管实例对象怎么修改属性值，对类的属性还是没有影响的."实际测试中都有影响的。下面是测试的代码和结果``
 class ClassA(): 	var1 = 'AAA'	 	def fun1(p): 		print('fun1'+p.var1)	 		 a = ClassA print(a.var1) a.var1 = 'CCC' print(a.var1) print(ClassA.var1)  

 是版本问题还是其他什么原因，麻烦楼主解惑。

**Comment by kszhaofeng** [comment]
多谢，已经找到问题，没有加括号，实际还是原来的类。而不是创建了对象。
