### ISSUE TITLE
也想问一下licence，能否在注明出处的情况下转载。

### ISSUE THREAD

**Issue by fendouai** [TwoWater/Python#42]
也想问一下licence，能否在注明出处的情况下转载。

**Comment by 54188-24** [comment]
是什么事情呢？
请回复邮件
若不是我自己订阅的
我会发邮件取消订阅




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fendouai"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 晚上9:04
收件人:&nbsp;"TwoWater/Python"<Python@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TwoWater/Python] 也想问一下licence，能否在注明出处的情况下转载。 (#42)




也想问一下licence，能否在注明出处的情况下转载。

**Comment by 54188-24** [comment]
您好，您说的是GitHub的python教程的开源项目吗？
我只是把那个项目下载的我的电脑的GitHub Desktop上面了，但是下载以后我有不会操作，所以一直就没有动，
并没有传播您的项目，应该不会出现需要标注出处的情况吧，如果对您产生了什么误会，我感到万分抱歉，并且会根据您的
合理建议做出相应的改正，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fendouai"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 晚上9:04
收件人:&nbsp;"TwoWater/Python"<Python@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TwoWater/Python] 也想问一下licence，能否在注明出处的情况下转载。 (#42)




也想问一下licence，能否在注明出处的情况下转载。

**Comment by TwoWater** [comment]
可以的，标明出处，不要随便更改内容（请保证内容一致性，保证质量）是可以转载的。

**Comment by foxsir** [comment]
> 可以的，标明出处，不要随便更改内容（请保证内容一致性，保证质量）是可以转载的。

您好，我把您的教程转载到这里了 https://www.programschool.com/，在此告知，也会注明 github 原始链接。如果有其他要求请回复我
