### ISSUE TITLE
https://github.com/TwoWater/Python/blob/master/Article/PythonBasis/python8/2.md这章节图挂了

### ISSUE THREAD

**Issue by BestElsie** [TwoWater/Python#43]
https://github.com/TwoWater/Python/blob/master/Article/PythonBasis/python8/2.md这章节图挂了

**Comment by TwoWater** [comment]
> [https://github.com/TwoWater/Python/blob/master/Article/PythonBasis/python8/2.md这章节图挂了](https://github.com/TwoWater/Python/blob/master/Article/PythonBasis/python8/2.md%E8%BF%99%E7%AB%A0%E8%8A%82%E5%9B%BE%E6%8C%82%E4%BA%86)

感谢提出问题，已修改，可以正常显示图片了。
